### ISSUE TITLE
Feature Request: Simplify reading NONMEM results

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/babelmixr2#43]
I have babelmixr2 successfully running a remote NONMEM using the function interface to copy the files to the remote system, run NONMEM, and pull the files back.

When the files get back, there are issues loading the results.  I'm trying to work through them, but I think that I'd prefer to rework the way that NONMEM results are loaded a bit so that it works more like:

1. Load all the files and store them at appropriate locations within the UI object.  For example, store them as "nonmemXML", "nonmemCov", "nonmemExt", "nonmemSdtab", and "nonmemPatab" or something like those (there may be a few more).  And, I'd like to do all of that in a single function like "rxUiGet.nonmemLoad()"
2. After that, don't look at the files anymore.
3. Update the NONMEM -> nlmixr2 information pull to use the new structures.

Any issues with that?  Anything that I'm missing where the way it's working is important for general nlmixr2 operation?

**Comment by mattfidler** [comment]
I wrote the functions as they are to:
- reduce the size of the UI object
- Produce hooks look at certain results

Because I spent so much time working to reduce the ui object size this seems like a step in the wrong direction to me.

I am unsure the advantage that the approach you are suggesting gives.  The other part is that it doesn't allow you to load certain pieces with a hook.

**Comment by mattfidler** [comment]
I typically try not to save anything in the model that doesn't need to be there.  And those that need to be there but are large compress.  

Since these files live at a place that doesn't disappear I don't really think they need to be there.  

This is inspired by the tidymodels idea of keeping the model object as small as possible.  There used to be a guide from Hadley that spoke of his philosophy here but I cannot seem to find it at the moment; (perhaps you have seen it?)

**Comment by billdenney** [comment]
Thanks for that explanation.  I tend not to assume that files will remain in the same place as that can be long-term fragile, but I do understand your (and tidymodel's) perspective.  Let me think a bit more about this for how I can solve my loading issues while simultaneously only including the needed results in the model.

**Comment by billdenney** [comment]
I've been thinking about this a bit more.  It would make sense to me to save the same information for all estimation types (which would mean effectively everything).  But, I can understand wanting to trim the size of the object, too.

How about we save the smaller bits (this may already be done) but not the larger bits?

Keep in the object:

* Objective function value
* Fixed effect parameter estimates and covariance matrices
* Per-subject random effect estimates (likely the full `patab` file); I realize that this is borderline

Do not keep in the object:

* The original dataset
* The output dataset (i.e. the `sdtab` file)

**Comment by mattfidler** [comment]
So these are already kept in the object:
- NONMEM objective function value (it is the objective function value used, you could add nlmixr focei objective function value too)
- Fixed parameter estimates
- Covariance matrices, but paired down to what nlmixr2 supports
- Per subject eta effects, but the patab type effects would be generated from nlmixr (and then they are included)

So I think that what you are requesting is already included...

**Comment by mattfidler** [comment]
If you want the full covariance matrix you can *still* read it in through a hook.

**Comment by mattfidler** [comment]
I am closing this for now.
