### ISSUE TITLE
rxode2 -> nlmixr2

### ISSUE THREAD

**Issue by dzianismr** [nlmixr2/babelmixr2#99]
I have a model implemented in rxode2. I would like to convert it to nlmixr2 model to fit the data.  I thought that as.nlmixr2( ) provides this functionality, however I am getting an error:
"Error: cannot figure out how to create an nlmixr2 object from the input"

Below is an example:

mod <- rxode2({
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
})  

mod_nlmixr2 <- as.nlmixr2( mod  )

Error: cannot figure out how to create an nlmixr2 object from the input
3. stop("cannot figure out how to create an nlmixr2 object from the input", call. = FALSE)
2. as.nlmixr2.default(mod)
1. as.nlmixr2(mod)

I have rxode2 2.0.14, nonmme2rx 0.1.2, babelmixr 0.1.1. What is the best way to convert rxode model to nlmixr model?

**Comment by mattfidler** [comment]
Hi @dzianismr 

the `as.nlmxir2` was not meant to transform generalized `rxode2` to `nlmixr2` compatible syntax, but to convert models imported from NONMEM to a nlmixr2 fit without rerunning the fit.  

I am afraid such a feature request is a bit too difficult to automate because of the free-form nature of `rxode2()`.

For now, I am going to close the issue, because this is known, and won't be fixed at the current time.

**Comment by dzianismr** [comment]
Thanks for the clarification @mattfidler. I am adding a link here to our separate disucssion, in case it may be of help for somebody. In the absence of generalied function rxode model can be converted to nlmixr model with piping https://github.com/nlmixr2/nlmixr2/discussions/194.
